<h2>Problem Statement</h2>
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:

The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below

    i 1 2 3 4 5 6 7 8 9 10
    ===== == == == == == == == == == ==
    Input 10 20 30 40 50 60 70 80 90 100
    y1 25 = (10+20+30+40)/4
    y2 35 = (20+30+40+50)/4
    y3 45 = (30+40+50+60)/4
    y4 55 = (40+50+60+70)/4
    y5 65 = (50+60+70+80)/4
    y6 75 = (60+70+80+90)/4
    y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Write a function to find moving average in an array over a window:

Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [1]:
import numpy as np
import pandas as pd


def calculate_moving_average(array, length, window_size):
    moving_average_list,count = [],0
    while(count < (length-window_size+1)):
        start,end,window_sum = count,count + window_size,0
        while(start<end):
            window_sum += array[start]
            start = start+1
        moving_average_list.append(round(window_sum/window_size,2))
        count = count+1
    return moving_average_list


input_array = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
length = len(input_array)
window_size = 3

moving_average_list = calculate_moving_average(input_array, length, window_size)
print(moving_average_list)

[5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]


<h2>Problem Statement</h2>
Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

    HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde.

In [2]:
import numpy as np

def generate_vandermond_matrix(input_array, n, increasing=False):
    if not increasing:
        opt_matrix = np.array([(x**(n-i-1)) for x in input_array for i in range(n)]).reshape(input_array.size,-1)
        #print(opt_matrix)
    else:
        opt_matrix = np.array([x**i for x in input_array for i in range(n)]).reshape(input_array.size,-1)
    return opt_matrix
        

inputvector = np.array([1,2,3,4,5])
no_col_opmat = 3
op_matx_dec_order = generate_vandermond_matrix(inputvector,no_col_opmat)
op_matx_inc_order = generate_vandermond_matrix(inputvector,no_col_opmat, True)
                               
print("The input array is:",inputvector,"\n")
print("Number of columns in output matrix should be:",no_col_opmat,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",op_matx_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",op_matx_inc_order,"\n")



inputvector = np.array([1,2,4,6,8,10])
no_col_opmat = 5
op_matx_dec_order = generate_vandermond_matrix(inputvector,no_col_opmat,False)
op_matx_inc_order = generate_vandermond_matrix(inputvector,no_col_opmat,True)

print("---------------------------------------------------------------\n")
print("The input array is:",inputvector,"\n")
print("Number of columns in output matrix should be:",no_col_opmat,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",op_matx_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",op_matx_inc_order,"\n")

The input array is: [1 2 3 4 5] 

Number of columns in output matrix should be: 3 

Vander matrix of the input array in decreasing order of powers:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 

Vander matrix of the input array in increasing order of powers:

 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]] 

---------------------------------------------------------------

The input array is: [ 1  2  4  6  8 10] 

Number of columns in output matrix should be: 5 

Vander matrix of the input array in decreasing order of powers:

 [[    1     1     1     1     1]
 [   16     8     4     2     1]
 [  256    64    16     4     1]
 [ 1296   216    36     6     1]
 [ 4096   512    64     8     1]
 [10000  1000   100    10     1]] 

Vander matrix of the input array in increasing order of powers:

 [[    1     1     1     1     1]
 [    1     2     4     8    16]
 [    1     4    16    64   256]
 [    1     6    36   216  1296]
 [    1     8    64   512  4096]
 [ 